# Generated by Django 2.2 on 2019-04-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='update_datetime',
            new_name='updated_datetime',
        ),
    ]
