# Generated by Django 2.2 on 2019-05-30 00:03

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='blogs'),
        ),
    ]
